<footer class="page-footer"><div class="footer content"><div class="block newsletter">
	<h2 class="footer-title">Contact Us</h2>
	<div class="content">
		<form class="form subscribe" novalidate="" action="http://mydevfactory.com/~rajiv/magento_virus/index.php/newsletter/subscriber/new/" method="post" data-mage-init="{&quot;validation&quot;: {&quot;errorClass&quot;: &quot;mage-error&quot;}}" id="newsletter-validate-detail">
			<div class="field newsletter">
				<label class="label" for="newsletter"><span>Sign Up for Our Newsletter:</span></label>
				<div class="control">
					<input name="email" id="newsletter" placeholder="Your mail" data-validate="{required:true, 'validate-email':true}" type="email">
				</div>
			</div>
			<div class="actions">
				<button class="action subscribe primary" title="Subscribe" type="submit">
				<span>GO</span>
				</button>
			</div>
		</form>
	</div>

	<div class="footer-social-media">
		<ul>
			<li><a href=""> <img src="images/fb.png" alt=""> </a></li>
			<li><a href=""> <img src="images/twt.png" alt=""> </a></li>
			<li><a href=""> <img src="images/printrest.png" alt=""> </a></li>
			<li><a href=""> <img src="images/you-tube.png" alt=""> </a></li>
		</ul>

		<div class="pay-pal"> <img src="images/paypal.png" alt=""> </div>
	</div>
</div>
<ul class="footer links">

<h2 class="footer-title">Information</h2>

	<li class="nav item">
		<a href="">Products</a>
	</li>
	<li class="nav item">
		<a href="">Antivirus</a>
	</li>
	<li class="nav item"><a href="">Microsoft Office </a></li>
	<li class="nav item"><a href="">Microsoft Windows</a></li>
	<li class="nav item"><a href="">Other Software</a></li>
	<li class="nav item"><a href="">About Us</a></li>
	<li class="nav item"><a href="">Downloads links</a></li>
	<li class="nav item"><a href="">Customer Service FAQ</a></li>
	<li class="nav item"><a href="">Returns Policy</a></li>
	<li class="nav item"><a href="">News & Events</a></li>
</ul>

<ul class="footer links">

<h2 class="footer-title">Why Buy from Us</h2>

	<li class="nav item">
		<a href="">Shipping and Returns</a>
	</li>

	<li class="nav item">
		<a href="">Secure Shopping</a>
	</li>

	<li class="nav item">
		<a href="">International Shipping</a>
	</li>

	<li class="nav item">
		<a href="">Affiliates</a>
	</li>

	<li class="nav item">
		<a href="">Group Sales</a>
	</li>

	</ul>

	<ul class="footer links">

<h2 class="footer-title">Products</h2>

	<li class="nav item">
		<a href="">Antivirus</a>
	</li>

	<li class="nav item">
		<a href="">Microsoft Office</a>
	</li>

	<li class="nav item">
		<a href="">Microsoft Windows</a>
	</li>

	<li class="nav item">
		<a href="">Other Software</a>
	</li>

	<li class="nav item">
		<a href="">Corporate Sales</a>
	</li>

	</ul>

	<ul class="footer links contact-us">

	<h2 class="footer-title">Contact Us</h2>

	<li>

	<p>Antivirus Kenya <br>
P.O Box 17199 00100 <br>
Nairobi Kenya</p>

<p>Tel: +254 0202400476  <br>
(Mon-Fri 8am-5pm)
</p>

<p>Mob: +254 722xxx xxx 733xxxxxx</p>

<p>Email: <a href=""> sales@antivirus.co.ke </a></p>

<p>Support: <a href="">support@antivirus.co.ke </a> </p>

<p>Whats App: 0722 xxx xxx.</p>
		
	</li>

	</ul>

</div>

</footer>

<div class="bottom-footer">

	<div class="footer-bottom-container">
		<div class="row">
			<div class="col-sm-6">
				<div class="reserved"> © Antivirus Kenya 2017, All rights reserved.</div>
			</div>
			<div class="col-sm-6">
				<div class="site-map">
					<ul>
						<li> <a href=""> Privacy Policy</a> </li> 
						<li> <span> | </span> </li>     
						<li> <a href=""> Sitemap </a> </li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>